:stats: {

        :scan_rate: {
                   :pair: [:scan_rate],
                   :units: "",
                   :color: ["#ffd700"],
                   :pname: "Scans/s"},

        :update_rate: {
                   :pair: [:update_rate],
                   :units: "",
                   :color: ["#daa520"],
                   :pname: "Updates/s"},

        :cell_read_rate: { :pair: [:cell_read_rate],
                       :units: "" ,
                       :color: ["#7cfc00"],
                       :pname: "Cells Read/s"},

        :cell_write_rate: {
                       :pair: [:cell_write_rate],
                       :units: "" ,
                       :color: ["#008000"],
                       :pname: "Cells Written/s"
                      },

        :byte_read_rate: {
                     :pair: [:byte_read_rate],
                     :color: ["#00ffff"],
                     :units: "Bytes",
                     :pname: "Table Bytes Read/s"},

        :byte_write_rate: {
                     :pair: [:byte_write_rate],
                     :color: ["#00008b"],
                     :units: "Bytes",
                     :pname: "Table Bytes Written/s"},

        :sync_rate: {
                   :pair: [:sync_rate],
                   :units: "",
                   :color: ["#ff4500"],
                   :pname: "Syncs/s"},

	:disk_read_iops: {
                     :pair: [:disk_read_iops],
                     :color: ["#ffd700"],
                     :units: "",
                     :pname: "Disk Activity - Read IOPS"},

	:disk_write_iops: {
                     :pair: [:disk_write_iops],
                     :color: ["#daa520"],
                     :units: "",
                     :pname: "Disk Activity - Write IOPS"},

        :disk_read_bytes: {
                    :pair: [:disk_read_bytes],
                    :color: ["#ff00ff"],
                    :units: "",
                    :pname: "Disk Activity - Read Bytes/s"},
       
        :disk_write_bytes: {
                     :pair: [:disk_write_bytes],
                     :color: ["#d02090"],
                     :units: "",
                     :pname: "Disk Activity - Write Bytes/s"},

	:net_rx_rate: {
                     :pair: [:net_rx_rate],
                     :color: ["#7cfc00"],
                     :units: "",
                     :pname: "Network Activity - RX Rate"},

	:net_tx_rate: {
                     :pair: [:net_tx_rate],
                     :color: ["#008000"],
                     :units: "",
                     :pname: "Network Activity - TX Rate"},

        :loadavg: {
                    :pair: [:loadavg],
                    :color: ["#ff0000"],
                    :units: "",
                    :pname: "Load Average"},

        :cpu_user: {
                    :pair: [:cpu_user],
                    :color: ["#7cfc00"],
                    :units: "",
                    :pname: "CPU User Time (%)"},

        :cpu_sys: {
                    :pair: [:cpu_sys],
                    :color: ["#ee6410"],
                    :units: "",
                    :pname: "CPU System Time (%)"},

        :scanner_count: { :pair: [:scanner_count],
                       :units: "" ,
                       :color: ["#ffd700"],
                       :pname: "Outstanding Scanner Count"},

        :file_count: { :pair: [:file_count],
                       :units: "" ,
                       :color: ["#8b4513"],
                       :pname: "CellStore Count"},

        :range_count: { :pair: [:range_count],
                       :units: "" ,
                       :color: ["#1e90ff"],
                       :pname: "Range Count"},

	:disk_used_pct: {
                    :pair: [:disk_used_pct],
                    :color: ["#008000"],
                    :units: "",
                    :pname: "Disk Used (%)"
                    },

        :vm_size: {
                  :pair: [:vm_size],
                  :color: ["#696969"],
                  :units: "KB",
                  :pname: "Virtual Memory Size"},

        :vm_resident: {
                  :pair: [:vm_resident],
                  :color: ["#000000"],
                  :units: "KB",
                  :pname: "Resident Memory Size"},

        :page_in: {
                  :pair: [:page_in],
                  :color: ["#FFC155"],
                  :units: "KB",
                  :pname: "Pages Swapped In"},

        :page_out: {
                  :pair: [:page_out],
                  :color: ["#FA9F00"],
                  :units: "KB",
                  :pname: "Pages Swapped Out"},

        :heap_size: {
                  :pair: [:heap_size],
                  :color: ["#ffd700"],
                  :units: "KB",
                  :pname: "Heap Size"},

        :heap_slack: {
                  :pair: [:heap_slack],
                  :color: ["#daa520"],
                  :units: "KB",
                  :pname: "Heap Slack Bytes"},

        :tracked_memory: {
                  :pair: [:tracked_memory],
                  :color: ["#8b008b"],
                  :units: "KB",
                  :pname: "Tracked Memory"},

	:bcache_fill: {
                    :pair: [:bcache_fill],
                    :color: ["#00ffff"],
                    :units: "",
                    :pname: "Block Cache Fill"
                    },

        :bcache_hit_pct: {
                    :pair: [:bcache_hit_pct],
                    :color: ["#0000ff"],
                    :units: "",
                    :pname: "Block Cache Hit Rate (%)"},
        :bcache_max_mem: {
                    :pair: [:bcache_max_mem],
                    :color: ["#00008b"],
                    :units: "",
                    :pname: "Block Cache Max Memory",
                    :flag: "1"  },

        :qcache_fill: {
                  :pair: [:qcache_fill],
                  :color: ["#ffa500"],
                  :units: "" ,
                  :pname: "Query Cache Fill"},

        :qcache_hit_pct: {
                     :pair: [:qcache_hit_pct],
                     :color: ["#fd7903"],
                     :units: "",
                     :pname: "Query Cache Hit Rate (%)"},

        :qcache_max_mem: {
                     :pair: [:qcache_max_mem],
                     :color: ["#ff4500"],
                     :units: "",
                     :pname: "Query Cache Max Memory"}
	
}
